import type { CompareReport, ConstraintDiff, TableMatch } from "./compare-types";
import type { ColumnSnapshot, ForeignKeySnapshot, TableSnapshot } from "./postgres";
import { compareSchemas, extractBaseType, isNarrowingType } from "./compare";
import { normalizeSimilarityText } from "./compare-utils";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export type SqlStatementKind =
  | "CREATE_TABLE"
  | "DROP_TABLE"
  | "ADD_COLUMN"
  | "DROP_COLUMN"
  | "ALTER_COLUMN_TYPE"
  | "ALTER_COLUMN_NULLABILITY"
  | "ALTER_COLUMN_DEFAULT"
  | "ADD_CONSTRAINT"
  | "DROP_CONSTRAINT"
  | "RENAME_TABLE"
  | "RENAME_COLUMN";

export type SqlStatement = {
  sql: string;
  description: string;
  kind: SqlStatementKind;
  severity: "breaking" | "safe" | "info";
  tableName: string;
  /**
   * True when running this statement destroys rows that exist only in the
   * target: DROP TABLE and DROP COLUMN. "breaking" is a wider category — a
   * rename or a narrowing type change is breaking but does not, on its own,
   * throw data away. Safe mode (see MigrationOptions) comments out exactly the
   * statements flagged here.
   */
  destructive: boolean;
};

export type MigrationOptions = {
  /**
   * When false (the default) every destructive statement is still generated and
   * shown, but rendered COMMENTED OUT, so running the script cannot drop a
   * table or a column. The user opts in explicitly to arm them.
   */
  allowDataLoss?: boolean;
  /**
   * Emit `ADD COLUMN IF NOT EXISTS` instead of a bare `ADD COLUMN`.
   *
   * Off for a forward migration: if the column is unexpectedly already there,
   * failing loudly is the right outcome. On for a rollback (generateRollback),
   * which has to run whether or not the forward script's drops were armed — in
   * safe mode nothing was dropped, so the restoring statements must be no-ops
   * rather than errors.
   */
  addColumnIfNotExists?: boolean;
};

export type MigrationScript = {
  statements: SqlStatement[];
  warnings: string[];
  sourceSchema: string;
  targetSchema: string;
  /** Whether destructive statements are armed in the rendered SQL. */
  allowDataLoss: boolean;
  /** How many statements would destroy data. */
  destructiveCount: number;
};

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

// Safely double-quote a PostgreSQL identifier, escaping any embedded quotes.
function q(identifier: string): string {
  return `"${identifier.replace(/"/g, '""')}"`;
}

function normalizeType(t: string): string {
  return normalizeSimilarityText(t);
}

function isNextvalDefault(defaultValue: string | null): boolean {
  return defaultValue !== null && /^\s*nextval\s*\(/i.test(defaultValue);
}

function supportsIdentityDefault(typeDisplay: string): boolean {
  const baseType = extractBaseType(typeDisplay);
  return baseType === "smallint" || baseType === "integer" || baseType === "bigint";
}

// Build the column definition fragment used in both CREATE TABLE and ADD COLUMN.
// e.g.  "email" character varying(255) NOT NULL DEFAULT 'anon'
function buildColumnDef(col: ColumnSnapshot): string {
  const shouldUseIdentity =
    isNextvalDefault(col.columnDefault) && supportsIdentityDefault(col.typeDisplay);

  let def = `${q(col.name)} ${col.typeDisplay}`;
  if (shouldUseIdentity) def += " GENERATED BY DEFAULT AS IDENTITY";
  if (!col.nullable) def += " NOT NULL";
  if (col.columnDefault !== null && !shouldUseIdentity) {
    def += ` DEFAULT ${col.columnDefault}`;
  }
  return def;
}

// Build a full CREATE TABLE statement for a table that is missing from B.
// FK constraints are intentionally omitted — they are emitted as separate
// ALTER TABLE ADD CONSTRAINT statements in Phase 4 so that the order in which
// tables appear in the script doesn't cause "referenced table doesn't exist yet"
// errors.
//
// The table name is written UNQUALIFIED (no schema prefix). The apply route runs
// `SET LOCAL search_path TO <targetSchema>` (target-only) before executing, so an
// unqualified name always resolves to the schema being applied to — at the
// original apply AND when the stored script is later replayed onto a different
// schema by Version Sync. A hard-coded schema qualifier would ignore search_path
// and silently hit the original schema on replay.
function buildCreateTable(table: TableSnapshot): string {
  const lines: string[] = table.columns.map((col) => `  ${buildColumnDef(col)}`);

  if (table.primaryKey) {
    lines.push(`  CONSTRAINT ${q(table.primaryKey.name)} ${table.primaryKey.definition}`);
  }
  for (const c of table.uniqueConstraints) {
    lines.push(`  CONSTRAINT ${q(c.name)} ${c.definition}`);
  }
  for (const c of table.checkConstraints) {
    lines.push(`  CONSTRAINT ${q(c.name)} ${c.definition}`);
  }
  for (const c of table.excludeConstraints) {
    lines.push(`  CONSTRAINT ${q(c.name)} ${c.definition}`);
  }

  return (
    `CREATE TABLE IF NOT EXISTS ${q(table.name)} (\n` +
    lines.join(",\n") +
    `\n);`
  );
}

// Build a FK definition from structured snapshot fields instead of using the
// raw pg_get_constraintdef string.
function buildFkDef(fk: ForeignKeySnapshot, sourceSchema: string): string {
  const localCols = fk.columns.map(q).join(", ");
  const refTable = fk.referencedTable ?? "";
  const refCols = fk.referencedColumns.map(q).join(", ");

  // A SELF-schema reference (points at the source schema, or unknown) is written
  // UNQUALIFIED so search_path scopes it to whatever schema the script is applied
  // to — including a later Version Sync replay onto a different schema (see
  // buildCreateTable). A GENUINE cross-schema reference — any other named schema,
  // even one that happens to share the target schema's name — KEEPS its explicit
  // qualifier so it stays pinned to that schema on replay.
  const refPrefix =
    fk.referencedSchema === sourceSchema || fk.referencedSchema == null
      ? ""
      : `${q(fk.referencedSchema)}.`;
  let def = `FOREIGN KEY (${localCols}) REFERENCES ${refPrefix}${q(refTable)} (${refCols})`;
  if (fk.onDelete !== "NO ACTION") def += ` ON DELETE ${fk.onDelete}`;
  if (fk.onUpdate !== "NO ACTION") def += ` ON UPDATE ${fk.onUpdate}`;
  return def;
}

// Look up a non-FK constraint definition from a table snapshot by kind + name.
// FK constraints are handled separately via buildFkDef.
function lookupConstraintDef(
  table: TableSnapshot,
  kind: ConstraintDiff["kind"],
  name: string
): { name: string; definition: string } | null {
  if (kind === "PRIMARY KEY") {
    return table.primaryKey?.name === name
      ? { name: table.primaryKey.name, definition: table.primaryKey.definition }
      : null;
  }
  if (kind === "UNIQUE") {
    const c = table.uniqueConstraints.find((c) => c.name === name);
    return c ? { name: c.name, definition: c.definition } : null;
  }
  if (kind === "CHECK") {
    const c = table.checkConstraints.find((c) => c.name === name);
    return c ? { name: c.name, definition: c.definition } : null;
  }
  if (kind === "EXCLUDE") {
    const c = table.excludeConstraints.find((c) => c.name === name);
    return c ? { name: c.name, definition: c.definition } : null;
  }
  return null;
}

// ---------------------------------------------------------------------------
// Per-table ALTER statements (Phase 3)
// ---------------------------------------------------------------------------

function alterStatementsForMatch(
  match: TableMatch,
  sourceSchema: string,
  addColumnIfNotExists: boolean
): { stmts: SqlStatement[]; fkStmts: SqlStatement[] } {
  const stmts: SqlStatement[] = [];
  // New FK ADD CONSTRAINTs are collected here and returned separately so the
  // caller can defer them to Phase 4 — AFTER every table's columns exist. An FK
  // added inline could reference a column that a later-processed table hasn't
  // gained yet, aborting the migration (issue #23).
  const fkStmts: SqlStatement[] = [];
  // After Phase 1 renames, the table in B carries A's name. Use that for all
  // subsequent ALTER TABLE statements so they reference the correct name.
  // Table names are UNQUALIFIED — search_path scopes them (see buildCreateTable).
  const tName = match.left.name;

  // ── 3a. Column renames ────────────────────────────────────────────────────
  // Must come before 3b/3c so later statements reference the post-rename name.
  for (const colMatch of match.columnMatches) {
    if (!colMatch.exact) {
      stmts.push({
        sql: `ALTER TABLE ${q(tName)} RENAME COLUMN ${q(colMatch.right.name)} TO ${q(colMatch.left.name)};`,
        description: `Rename column "${colMatch.right.name}" → "${colMatch.left.name}" in "${tName}" (${colMatch.score}% match — verify this is a rename before running)`,
        kind: "RENAME_COLUMN",
        severity: "breaking",
        tableName: tName,
        destructive: false,
      });
    }
  }

  // ── 3b. Add columns that exist in A but are absent from B ─────────────────
  for (const col of match.columnsOnlyInA) {
    // NOT NULL + no default will fail on a non-empty table because PostgreSQL
    // can't fill existing rows. Flag it so the user knows to add a DEFAULT or
    // run on an empty table.
    const risky = !col.nullable && col.columnDefault === null;
    stmts.push({
      sql:
        `ALTER TABLE ${q(tName)} ADD COLUMN ` +
        (addColumnIfNotExists ? "IF NOT EXISTS " : "") +
        `${buildColumnDef(col)};`,
      description:
        `Add column "${col.name}" (${col.typeDisplay}) to "${tName}"` +
        (risky ? " — WARNING: NOT NULL with no default, will fail on a non-empty table" : ""),
      kind: "ADD_COLUMN",
      severity: risky ? "breaking" : "safe",
      tableName: tName,
      destructive: false,
    });
  }

  // ── 3c. Type, nullability and default changes on matched columns ──────────
  for (const colMatch of match.columnMatches) {
    // After a rename (3a), this column is now called colMatch.left.name in B.
    const colName = colMatch.left.name;
    const leftNorm = normalizeType(colMatch.left.typeDisplay);
    const rightNorm = normalizeType(colMatch.right.typeDisplay);

    if (leftNorm !== rightNorm) {
      const baseChanged =
        extractBaseType(colMatch.left.typeDisplay) !== extractBaseType(colMatch.right.typeDisplay);
      // Same base type but a SMALLER size/precision (e.g. varchar(200) →
      // varchar(100), numeric(10,2) → numeric(6,2)). This is NOT a safe widen:
      // PostgreSQL rejects the change if any existing value exceeds the new
      // size, so it is a breaking change that must be flagged.
      const narrowing =
        !baseChanged &&
        isNarrowingType(colMatch.right.typeDisplay, colMatch.left.typeDisplay);
      // USING is needed when PostgreSQL can't cast automatically (cross-type changes).
      // Same-family widenings (e.g. varchar(100) → varchar(200)) don't need it.
      const usingSuffix = baseChanged
        ? ` USING ${q(colName)}::${colMatch.left.typeDisplay}`
        : "";

      let description: string;
      let severity: SqlStatement["severity"];
      if (baseChanged) {
        description = `Change type of "${colName}" in "${tName}": ${colMatch.right.typeDisplay} → ${colMatch.left.typeDisplay} (may require data conversion)`;
        severity = "breaking";
      } else if (narrowing) {
        description = `Narrow "${colName}" in "${tName}": ${colMatch.right.typeDisplay} → ${colMatch.left.typeDisplay} — WARNING: will fail if any existing value exceeds the new size`;
        severity = "breaking";
      } else {
        description = `Widen "${colName}" in "${tName}": ${colMatch.right.typeDisplay} → ${colMatch.left.typeDisplay}`;
        severity = "safe";
      }

      stmts.push({
        sql: `ALTER TABLE ${q(tName)} ALTER COLUMN ${q(colName)} TYPE ${colMatch.left.typeDisplay}${usingSuffix};`,
        description,
        kind: "ALTER_COLUMN_TYPE",
        severity,
        tableName: tName,
        destructive: false,
      });
    }

    if (colMatch.left.nullable !== colMatch.right.nullable) {
      if (!colMatch.left.nullable) {
        stmts.push({
          sql: `ALTER TABLE ${q(tName)} ALTER COLUMN ${q(colName)} SET NOT NULL;`,
          description: `Enforce NOT NULL on "${colName}" in "${tName}" — WARNING: will fail if existing rows contain NULLs; backfill first`,
          kind: "ALTER_COLUMN_NULLABILITY",
          severity: "breaking",
          tableName: tName,
          destructive: false,
        });
      } else {
        stmts.push({
          sql: `ALTER TABLE ${q(tName)} ALTER COLUMN ${q(colName)} DROP NOT NULL;`,
          description: `Allow nulls on "${colName}" in "${tName}"`,
          kind: "ALTER_COLUMN_NULLABILITY",
          severity: "safe",
          tableName: tName,
          destructive: false,
        });
      }
    }

    // Default value change. Defaults are schema-relative here (own-schema
    // qualifier stripped at snapshot time), so SET DEFAULT resolves against the
    // target via search_path.
    const leftSerial = isNextvalDefault(colMatch.left.columnDefault);
    const rightSerial = isNextvalDefault(colMatch.right.columnDefault);
    const leftDefault = colMatch.left.columnDefault?.trim() || null;
    const rightDefault = colMatch.right.columnDefault?.trim() || null;
    if (leftSerial && rightSerial) {
      // Both serial/identity — sequence-name noise only, nothing to emit.
    } else if (leftSerial) {
      // Source is serial/identity, target isn't. Synthesizing a sequence + default
      // + ownership safely is out of scope, so surface it for manual work rather
      // than emit a SET DEFAULT that points at a sequence the target may not have.
      stmts.push({
        sql: `-- MANUAL: "${colName}" in "${tName}" is serial/identity in the source (default ${leftDefault}); add a matching sequence or IDENTITY by hand.`,
        description: `"${colName}" needs a serial/identity default added manually`,
        kind: "ALTER_COLUMN_DEFAULT",
        severity: "info",
        tableName: tName,
        destructive: false,
      });
    } else if (leftDefault !== rightDefault) {
      // Neither is source-serial (target may be serial → this replaces/drops it).
      if (leftDefault === null) {
        stmts.push({
          sql: `ALTER TABLE ${q(tName)} ALTER COLUMN ${q(colName)} DROP DEFAULT;`,
          description: `Drop default on "${colName}" in "${tName}"`,
          kind: "ALTER_COLUMN_DEFAULT",
          severity: "safe",
          tableName: tName,
          destructive: false,
        });
      } else {
        stmts.push({
          sql: `ALTER TABLE ${q(tName)} ALTER COLUMN ${q(colName)} SET DEFAULT ${leftDefault};`,
          description: `Set default on "${colName}" in "${tName}" to ${leftDefault}`,
          kind: "ALTER_COLUMN_DEFAULT",
          severity: "safe",
          tableName: tName,
          destructive: false,
        });
      }
    }
  }

  // ── 3d. Constraint diffs ──────────────────────────────────────────────────
  // Drop order: FKs first so we remove the dependency before anything else.
  const toDrop = match.constraintDiffs.filter(
    (d) => d.status === "onlyB" || d.status === "changedDefinition"
  );
  const dropFksFirst = toDrop.filter((d) => d.kind === "FOREIGN KEY");
  const dropRest = toDrop.filter((d) => d.kind !== "FOREIGN KEY");

  for (const diff of [...dropFksFirst, ...dropRest]) {
    const constraintName = diff.rightName ?? "";
    if (!constraintName) continue;
    stmts.push({
      sql: `ALTER TABLE ${q(tName)} DROP CONSTRAINT IF EXISTS ${q(constraintName)};`,
      description: `Drop ${diff.kind} "${constraintName}" from "${tName}"`,
      kind: "DROP_CONSTRAINT",
      severity: diff.kind === "FOREIGN KEY" || diff.kind === "PRIMARY KEY" ? "breaking" : "info",
      tableName: tName,
      destructive: false,
    });
  }

  // Add order: non-FKs here; FK ADDs are deferred into fkStmts (Phase 4) so they
  // run after every table's ADD COLUMN across ALL matched/created tables.
  const toAdd = match.constraintDiffs.filter(
    (d) => d.status === "onlyA" || d.status === "changedDefinition"
  );
  const addNonFks = toAdd.filter((d) => d.kind !== "FOREIGN KEY");
  const addFks = toAdd.filter((d) => d.kind === "FOREIGN KEY");

  for (const diff of addNonFks) {
    const cName = diff.leftName ?? "";
    if (!cName) continue;
    const found = lookupConstraintDef(match.left, diff.kind, cName);
    if (!found) continue;
    stmts.push({
      sql: `ALTER TABLE ${q(tName)} ADD CONSTRAINT ${q(found.name)} ${found.definition};`,
      description: `Add ${diff.kind} "${found.name}" to "${tName}"`,
      kind: "ADD_CONSTRAINT",
      severity: diff.kind === "PRIMARY KEY" ? "breaking" : "info",
      tableName: tName,
      destructive: false,
    });
  }

  for (const diff of addFks) {
    const fkName = diff.leftName ?? "";
    const fk = match.left.foreignKeys.find((f) => f.name === fkName);
    if (!fk) continue;
    fkStmts.push({
      sql: `ALTER TABLE ${q(tName)} ADD CONSTRAINT ${q(fk.name)} ${buildFkDef(fk, sourceSchema)};`,
      description: `Add FK "${fk.name}" to "${tName}"`,
      kind: "ADD_CONSTRAINT",
      severity: "info",
      tableName: tName,
      destructive: false,
    });
  }

  // ── 3e. Drop columns that exist in B but not in A ─────────────────────────
  // Destructive: removes the column and its data. Emitted last (after the
  // constraint drops above) and with CASCADE + IF EXISTS so it never trips over
  // a dependent index/constraint and stays idempotent on re-run.
  for (const col of match.columnsOnlyInB) {
    stmts.push({
      sql: `ALTER TABLE ${q(tName)} DROP COLUMN IF EXISTS ${q(col.name)} CASCADE;`,
      description: `Drop column "${col.name}" from "${tName}" — WARNING: removes the column and all its data`,
      kind: "DROP_COLUMN",
      severity: "breaking",
      tableName: tName,
      destructive: true,
    });
  }

  return { stmts, fkStmts };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate a migration script that brings B (right/target) in sync with A (left/source).
 * The returned statements are ordered so they can be run top-to-bottom without
 * manual reordering:
 *
 *   Phase 1 — Rename tables in B to match A's names
 *   Phase 2 — CREATE TABLE for tables only in A (FK constraints queued for Phase 4)
 *   Phase 3 — ALTER matched tables (renames → adds → type/null → constraints → DROP COLUMN)
 *   Phase 4 — FK constraints for newly created tables (safe to add now that all tables exist)
 *   Phase 5 — DROP TABLE for tables only in B (destructive, done last)
 *
 * This is a COMPLETE sync: it always GENERATES the destructive statements
 * (DROP TABLE / DROP COLUMN) needed to fully match A, so the report can show
 * the user exactly what a full sync would remove. Whether those statements are
 * ARMED in the rendered SQL is a separate decision:
 *
 *   allowDataLoss: false  (default)  destructive statements are rendered
 *                                    commented out — running the script cannot
 *                                    drop a table or a column
 *   allowDataLoss: true              they are rendered live
 *
 * Nothing is silently skipped in either mode: renderMigrationScript states how
 * many statements were held back and how to arm them.
 */
export function generateMigration(
  report: CompareReport,
  options: MigrationOptions = {},
): MigrationScript {
  const allowDataLoss = options.allowDataLoss === true;
  const sourceSchema = report.left.schema;
  const statements: SqlStatement[] = [];
  const warnings: string[] = [];

  // ── Phase 1: Rename tables ────────────────────────────────────────────────
  // Similarity-matched tables have different names in A and B.
  // We rename B's table to A's name so subsequent ALTER TABLE statements work.
  for (const match of report.matchedTables) {
    if (!match.exact) {
      statements.push({
        sql: `ALTER TABLE ${q(match.right.name)} RENAME TO ${q(match.left.name)};`,
        description: `Rename table "${match.right.name}" → "${match.left.name}" (${match.score}% similarity — verify this is a rename and not two unrelated tables)`,
        kind: "RENAME_TABLE",
        severity: "breaking",
        tableName: match.right.name,
        destructive: false,
      });
    }
  }

  // ── Phase 2: CREATE TABLE for tables only in A ────────────────────────────
  // FK constraints are queued separately (fkStatements) and appended in Phase 4
  // so the ordering of CREATE TABLE statements doesn't matter.
  const fkStatements: SqlStatement[] = [];

  for (const table of report.tablesOnlyInA) {
    statements.push({
      sql: buildCreateTable(table),
      description: `Create table "${table.name}"`,
      kind: "CREATE_TABLE",
      severity: "info",
      tableName: table.name,
      destructive: false,
    });

    for (const fk of table.foreignKeys) {
      fkStatements.push({
        sql: `ALTER TABLE ${q(table.name)} ADD CONSTRAINT ${q(fk.name)} ${buildFkDef(fk, sourceSchema)};`,
        description: `Add FK "${fk.name}" to "${table.name}"`,
        kind: "ADD_CONSTRAINT",
        severity: "info",
        tableName: table.name,
        destructive: false,
      });
    }
  }

  // ── Phase 3: Alter matched tables ─────────────────────────────────────────
  // Each match yields immediate ALTERs plus any new-FK ADDs, which are deferred
  // into the Phase 4 bucket so they run after every table's columns exist.
  for (const match of report.matchedTables) {
    const { stmts, fkStmts } = alterStatementsForMatch(
      match,
      sourceSchema,
      options.addColumnIfNotExists === true,
    );
    statements.push(...stmts);
    fkStatements.push(...fkStmts);
  }

  // ── Phase 4: FK constraints (new tables + matched tables) ─────────────────
  // All tables exist and all columns have been added, so every FK is safe now.
  statements.push(...fkStatements);

  // ── Phase 5: Drop tables that exist in B but not in A ─────────────────────
  // Destructive: removes the table and all its data. Done LAST so the additive
  // and alter work above never trips over a missing table, and any FK that
  // referenced this table was already dropped in Phase 3. CASCADE clears any
  // remaining dependents; IF EXISTS keeps it idempotent on re-run.
  for (const table of report.tablesOnlyInB) {
    statements.push({
      sql: `DROP TABLE IF EXISTS ${q(table.name)} CASCADE;`,
      description: `Drop table "${table.name}" — WARNING: removes the table and all its data`,
      kind: "DROP_TABLE",
      severity: "breaking",
      tableName: table.name,
      destructive: true,
    });
  }

  const destructiveCount = statements.filter((s) => s.destructive).length;
  if (destructiveCount > 0 && !allowDataLoss) {
    warnings.push(
      `${destructiveCount} destructive statement${destructiveCount === 1 ? " is" : "s are"} ` +
        `commented out. Enable "allow data loss" to include ${destructiveCount === 1 ? "it" : "them"}.`,
    );
  }

  return {
    statements,
    warnings,
    sourceSchema: `${report.left.database}.${report.left.schema}`,
    targetSchema: `${report.right.database}.${report.right.schema}`,
    allowDataLoss,
    destructiveCount,
  };
}

// Prefix every line of a statement with "-- " so it is inert when executed.
function commentOut(sql: string): string {
  return sql
    .split("\n")
    .map((line) => `-- ${line}`)
    .join("\n");
}

// Render the migration script as a plain SQL text string with inline comments.
// Each statement is preceded by a comment showing its severity and description.
//
// When script.allowDataLoss is false, statements flagged destructive are
// rendered commented out. This is the single point where a generated script
// becomes able to destroy data, so the decision is made here and nowhere else.
export function renderMigrationScript(script: MigrationScript): string {
  const breaking = script.statements.filter((s) => s.severity === "breaking").length;
  const safe = script.statements.filter((s) => s.severity === "safe").length;
  const info = script.statements.filter((s) => s.severity === "info").length;
  const held = script.allowDataLoss ? 0 : script.destructiveCount;

  const header = [
    `-- ================================================================`,
    `-- Migration: ${script.sourceSchema}  →  ${script.targetSchema}`,
    `-- Direction: modifies the RIGHT/TARGET schema to match the LEFT/SOURCE schema`,
    `-- Statements: ${script.statements.length}  (${breaking} breaking · ${safe} safe · ${info} info)`,
  ];

  if (held > 0) {
    header.push(
      `--`,
      `-- SAFE MODE IS ON. ${held} destructive statement${held === 1 ? "" : "s"} ` +
        `(DROP TABLE / DROP COLUMN) ${held === 1 ? "is" : "are"} commented out below`,
      `-- and will NOT run. Each one is marked [NOT EXECUTED]. To apply them,`,
      `-- re-run the comparison with "allow data loss" enabled, or uncomment them`,
      `-- by hand in the script editor after checking the data is expendable.`,
    );
  } else if (script.destructiveCount > 0) {
    header.push(
      `--`,
      `-- DATA LOSS IS ARMED. ${script.destructiveCount} statement` +
        `${script.destructiveCount === 1 ? "" : "s"} below will permanently remove`,
      `-- tables or columns and every row in them. Review each one before running.`,
    );
  }

  header.push(`-- ================================================================`);
  const headerText = header.join("\n");

  if (script.statements.length === 0) {
    return `${headerText}\n\n-- No changes needed.`;
  }

  const body = script.statements
    .map((stmt) => {
      const muted = stmt.destructive && !script.allowDataLoss;
      const tag = muted ? "NOT EXECUTED — " : "";
      return (
        `-- [${tag}${stmt.severity.toUpperCase()}] ${stmt.description}\n` +
        (muted ? commentOut(stmt.sql) : stmt.sql)
      );
    })
    .join("\n\n");

  return `${headerText}\n\n${body}`;
}

// ---------------------------------------------------------------------------
// Rollback / down scripts
// ---------------------------------------------------------------------------

export type RollbackScript = {
  /** The statements that undo the forward migration, in runnable order. */
  statements: SqlStatement[];
  warnings: string[];
  /** Label of the schema the rollback runs against — the same target as the migration. */
  targetSchema: string;
  /** Label of the schema the migration synced from, for the header only. */
  sourceSchema: string;
  /**
   * Structure the rollback puts back but cannot refill. Tables are bare names;
   * columns are written "table.column". These are exactly the things the
   * forward migration's DROP statements removed.
   */
  emptyOnRestore: { tables: string[]; columns: string[] };
  /**
   * Tables the rollback DROPS because the forward migration created them. Any
   * row written into one of these since the migration ran is lost.
   */
  dropsCreated: string[];
  /** True when the rollback restores the target exactly, data included. */
  lossless: boolean;
  /** Whether the forward migration this undoes had its drops armed. */
  forwardAllowedDataLoss: boolean;
};

/**
 * Build the down script for the migration generateMigration() produces from the
 * same report.
 *
 * Undoing "make the target look like the source" is the same problem as the
 * migration itself with the two sides swapped, so this runs the comparison
 * backwards and reuses the whole forward generator on the result instead of
 * hand-writing an inverse for each of the sixteen statement shapes. A dropped
 * column comes back as an ADD COLUMN, a created table becomes a DROP TABLE, a
 * widened type narrows again, a rename renames back.
 *
 * Two things a down script genuinely cannot do, both stated in the rendered
 * header rather than hidden:
 *
 *   - It restores structure, never data. A table the migration dropped comes
 *     back empty; a column comes back full of nulls or its default.
 *   - Dropping a table the migration created destroys anything written into it
 *     since. Those drops are armed, because a rollback that leaves half the
 *     migration in place is not a rollback.
 *
 * Pass the same allowDataLoss the forward migration used. It does not change
 * which statements are emitted — the restoring ones are written idempotently so
 * they are inert when the forward script never dropped anything — it only
 * changes what the header claims was lost.
 */
export function generateRollback(
  report: CompareReport,
  options: MigrationOptions = {},
): RollbackScript {
  const forwardAllowedDataLoss = options.allowDataLoss === true;

  // The comparison, backwards: the target's ORIGINAL state becomes the source
  // to restore, and the post-migration state (which matches the source) becomes
  // the thing to change.
  const reverseReport = compareSchemas(report.right, report.left);
  const inverse = generateMigration(reverseReport, {
    allowDataLoss: true,
    addColumnIfNotExists: true,
  });

  // What the forward migration destroyed, read off the ORIGINAL report so the
  // header describes the migration the user actually ran.
  const emptyTables = report.tablesOnlyInB.map((t) => t.name);
  const emptyColumns: string[] = [];
  for (const match of report.matchedTables) {
    for (const col of match.columnsOnlyInB) {
      emptyColumns.push(`${match.left.name}.${col.name}`);
    }
  }
  const dropsCreated = report.tablesOnlyInA.map((t) => t.name);

  const restoredCount = emptyTables.length + emptyColumns.length;
  const lossless = restoredCount === 0 && dropsCreated.length === 0;

  const warnings: string[] = [];
  if (restoredCount > 0 && forwardAllowedDataLoss) {
    warnings.push(
      `The rollback recreates ${restoredCount} dropped object${restoredCount === 1 ? "" : "s"} ` +
        `but cannot restore the rows they held.`,
    );
  }
  if (restoredCount > 0 && !forwardAllowedDataLoss) {
    warnings.push(
      `The migration ran in safe mode, so nothing was dropped and the ` +
        `${restoredCount} restoring statement${restoredCount === 1 ? "" : "s"} ` +
        `will do nothing.`,
    );
  }
  if (dropsCreated.length > 0) {
    warnings.push(
      `The rollback drops ${dropsCreated.length} table${dropsCreated.length === 1 ? "" : "s"} ` +
        `the migration created. Rows written into ${dropsCreated.length === 1 ? "it" : "them"} since are lost.`,
    );
  }
  const unconfirmed = reverseReport.possibleTableMatches.length;
  if (unconfirmed > 0) {
    warnings.push(
      `The reverse comparison could not confirm ${unconfirmed} table ` +
        `rename${unconfirmed === 1 ? "" : "s"}. Where it was unsure it emitted a ` +
        `CREATE plus a DROP instead of a RENAME, so the rollback recreates the ` +
        `table empty rather than renaming it back. Read those statements before running.`,
    );
  }

  return {
    statements: inverse.statements,
    warnings,
    targetSchema: `${report.right.database}.${report.right.schema}`,
    sourceSchema: `${report.left.database}.${report.left.schema}`,
    emptyOnRestore: { tables: emptyTables, columns: emptyColumns },
    dropsCreated,
    lossless,
    forwardAllowedDataLoss,
  };
}

// Wrap a comma-joined list so a header comment line stays readable.
function commentList(items: string[], indent: string): string[] {
  const lines: string[] = [];
  let current = "";
  for (const item of items) {
    const next = current ? `${current}, ${item}` : item;
    if (next.length > 64 && current) {
      lines.push(`${indent}${current}`);
      current = item;
    } else {
      current = next;
    }
  }
  if (current) lines.push(`${indent}${current}`);
  return lines;
}

/**
 * Render a rollback as plain SQL.
 *
 * Nothing here is ever commented out. A rollback whose statements do not run is
 * not a rollback, so the honesty lives in the header instead: it says what the
 * script restores, what it cannot restore, and what it destroys.
 */
export function renderRollbackScript(script: RollbackScript): string {
  const breaking = script.statements.filter((s) => s.severity === "breaking").length;
  const safe = script.statements.filter((s) => s.severity === "safe").length;
  const info = script.statements.filter((s) => s.severity === "info").length;

  const header = [
    `-- ================================================================`,
    `-- ROLLBACK (down script)`,
    `-- Undoes the migration ${script.sourceSchema}  →  ${script.targetSchema}`,
    `-- Runs against: ${script.targetSchema}`,
    `-- Statements: ${script.statements.length}  (${breaking} breaking · ${safe} safe · ${info} info)`,
    `--`,
  ];

  if (script.statements.length === 0) {
    header.push(
      `-- The migration changed nothing, so there is nothing to undo.`,
      `-- ================================================================`,
    );
    return header.join("\n");
  }

  if (script.lossless) {
    header.push(
      `-- This rollback is complete. The migration dropped nothing and created`,
      `-- nothing, so running this restores the target exactly as it was.`,
    );
  } else {
    header.push(`-- THIS RESTORES STRUCTURE, NOT DATA.`);
  }

  const { tables, columns } = script.emptyOnRestore;
  if (tables.length > 0 || columns.length > 0) {
    if (script.forwardAllowedDataLoss) {
      header.push(`--`, `-- Recreated EMPTY — the rows they held are gone:`);
    } else {
      header.push(
        `--`,
        `-- The migration ran in SAFE MODE, so it dropped none of the following.`,
        `-- These statements are written idempotently and will do nothing unless`,
        `-- the drops were armed or run by hand:`,
      );
    }
    if (tables.length > 0) {
      header.push(`--   tables:`, ...commentList(tables, "--     "));
    }
    if (columns.length > 0) {
      header.push(`--   columns:`, ...commentList(columns, "--     "));
    }
  }

  if (script.dropsCreated.length > 0) {
    header.push(
      `--`,
      `-- DROPPED — created by the migration, so any row written into them since`,
      `-- the migration ran is lost:`,
      ...commentList(script.dropsCreated, "--     "),
    );
  }

  header.push(
    `--`,
    `-- Run this only if the migration was applied in full. Applying it to a`,
    `-- target the migration never touched will fail or do nothing.`,
    `-- ================================================================`,
  );

  const body = script.statements
    .map((stmt) => `-- [${stmt.severity.toUpperCase()}] ${stmt.description}\n${stmt.sql}`)
    .join("\n\n");

  return `${header.join("\n")}\n\n${body}`;
}
