/** @jest-environment jsdom */

/**
 * The offer at the top of the Script Editor to load a script saved on a
 * Performance tab.
 *
 * It is an offer and never a load. The editor may already hold work nobody has
 * saved, and a hand-over that filled the boxes in by itself would destroy it
 * with no way back — so the banner says what loading would do, and waits. Which
 * is why most of what it draws is sentences: what the script is, where it would
 * point the editor, whether a rollback came with it, and — only when there is
 * something to lose — that loading overwrites what is there.
 *
 * Two of those sentences are conditional on facts the banner cannot see at
 * first. The saved connections arrive over the network after the page does, and
 * until they do the banner cannot say whether the connection this script was
 * made on still exists, so Load waits rather than guess. And the draft carries
 * its connection id as TEXT, the way the editor's picker holds it, while the
 * connection list carries numbers — a comparison that forgot that would quietly
 * report every connection as deleted.
 *
 * The draft really is read out of this tab's sessionStorage below, through the
 * hook the component uses, rather than passed in as a prop: the reading is the
 * only part of the hand-over the banner owns.
 *
 * What is NOT here:
 *  - The storage itself: saving, reading, forgetting, a browser that refuses
 *    all three, what counts as a usable draft, how statements are counted, and
 *    planDraftLoad. All of it is tests/migration-draft.test.ts.
 *  - The Performance side that writes the draft:
 *    tests/component-fix-script-builder.test.tsx.
 *  - What the editor does once the draft is handed over. The page's loadDraft
 *    has no test of its own; planDraftLoad, which decides what it sets, is
 *    covered in tests/migration-draft.test.ts, and the screen around it is
 *    tests/page-script-editor.test.tsx.
 *  - The singular/plural rule, which is tests/concurrency.test.ts. What is
 *    checked below is that the banner counts statements rather than lines and
 *    puts the count through that rule at all.
 */

import "@testing-library/jest-dom";
import { fireEvent, render, screen } from "@testing-library/react";

import { MigrationDraftBanner } from "@/components/studio/MigrationDraftBanner";
import { MIGRATION_DRAFT_KEY, type MigrationDraft } from "@/lib/migration-draft";

// A draft in the shape a Performance tab saves: a header comment, then each
// change under the finding it fixes.
const ONE_STATEMENT: MigrationDraft = {
  sql:
    "-- Generated by Schema Studio. Review before running.\n\n" +
    "-- Foreign key has no index (orders.customer_id)\n" +
    'CREATE INDEX "orders_customer_id_idx" ON "public"."orders" ("customer_id");\n',
  rollbackSql: 'DROP INDEX "public"."orders_customer_id_idx";\n',
  description: "Performance fixes for public: Foreign key has no index (orders.customer_id)",
  connectionId: "3",
  schema: "public",
  createdAt: "2026-09-14T10:32:45.000Z",
};

// Two changes, and no rollback because one of them has no statement that undoes
// it — which is the only way a saved draft ends up without one.
const TWO_STATEMENTS: MigrationDraft = {
  ...ONE_STATEMENT,
  sql:
    "-- Generated by Schema Studio. Review before running.\n\n" +
    "-- Foreign key has no index (orders.customer_id)\n" +
    'CREATE INDEX "orders_customer_id_idx" ON "public"."orders" ("customer_id");\n\n' +
    "-- Column is text where the values are all integers (orders.qty)\n" +
    'ALTER TABLE "public"."orders" ALTER COLUMN "qty" TYPE integer USING "qty"::integer;\n',
  rollbackSql: null,
};

// The editor's own list, as GET /api/connections gives it: numeric ids, while
// the draft's connectionId is the text the picker holds.
const CONNECTIONS = [
  { id: 3, name: "Billing prod" },
  { id: 8, name: "Analytics" },
];

const onLoad = jest.fn();

beforeEach(() => {
  onLoad.mockClear();
  window.sessionStorage.clear();
});

/** Put a draft where the hook will find it, exactly as Performance leaves it. */
function saved(draft: MigrationDraft = ONE_STATEMENT) {
  window.sessionStorage.setItem(MIGRATION_DRAFT_KEY, JSON.stringify(draft));
}

type Overrides = Partial<Parameters<typeof MigrationDraftBanner>[0]>;

function banner(over: Overrides = {}) {
  return render(
    <MigrationDraftBanner
      connections={CONNECTIONS}
      connectionsLoaded
      editorHasContent={false}
      onLoad={onLoad}
      {...over}
    />
  );
}

const offer = () => screen.queryByRole("region", { name: "A script from Performance" });
const panel = () => screen.getByRole("region", { name: "A script from Performance" });
const words = (el: Element | null) => (el?.textContent ?? "").replace(/\s+/g, " ").trim();
const headline = () => words(panel().querySelector(".font-semibold"));
const paragraphs = () => Array.from(panel().querySelectorAll("p")).map((p) => words(p));
const stored = () => window.sessionStorage.getItem(MIGRATION_DRAFT_KEY);
const discard = () => screen.getByRole("button", { name: "Discard" });
const load = () => screen.getByRole("button", { name: "Load into the editor" });

describe("when there is nothing waiting", () => {
  test("says nothing at all", () => {
    const view = banner();
    expect(view.container).toBeEmptyDOMElement();
  });

  test("and nothing when what is stored is not a draft", () => {
    // Storage is the person's own browser and can hold anything — an older
    // version of this app's draft, or something typed in by hand. What counts
    // as usable is decided in lib/migration-draft; what matters here is that an
    // unusable one leaves no empty offer on the screen.
    window.sessionStorage.setItem(MIGRATION_DRAFT_KEY, "half a draft {");
    const view = banner();
    expect(view.container).toBeEmptyDOMElement();
  });
});

describe("what the offer says", () => {
  test("names the script by what it runs and what it runs against", () => {
    saved();
    banner();
    expect(headline()).toBe("A script from Performance is waiting: 1 statement for schema public.");
  });

  test("counts the statements rather than the lines it spans", () => {
    // The draft is mostly comments — the header and one line per finding — so a
    // count of anything but statements would be several times too big.
    saved(TWO_STATEMENTS);
    banner();
    expect(headline()).toBe("A script from Performance is waiting: 2 statements for schema public.");
  });

  test("says where loading would point the editor", () => {
    saved();
    banner();
    expect(paragraphs()[0]).toBe(
      "Loading it points the editor at Billing prod, schema public, and fills in the SQL and the description. " +
        "The rollback is filled in too: the statements that undo each change, last change first."
    );
  });

  test("finds that connection although the draft holds its id as text", () => {
    // The draft carries "3" and the list carries 3. A comparison that skipped
    // the conversion would match nothing and report a live connection as
    // deleted, which is the sentence below.
    saved();
    banner();
    expect(paragraphs()[0]).toContain("points the editor at Billing prod");
  });

  test("says so when the connection it was made on has been deleted since", () => {
    saved();
    banner({ connections: [{ id: 8, name: "Analytics" }] });
    expect(paragraphs()[0]).toBe(
      "The connection it was made on is no longer saved. After loading, pick the connection " +
        "that holds schema public: every statement names that schema. " +
        "The rollback is filled in too: the statements that undo each change, last change first."
    );
  });

  test("claims nothing about the connection before the list has arrived", () => {
    // The list is fetched, so for the first moments of the page it is empty and
    // not yet loaded. Saying the connection was deleted then would be a lie
    // that resolves itself a second later.
    saved();
    banner({ connections: [], connectionsLoaded: false });
    expect(paragraphs()[0]).toBe(
      "Loading it fills in the SQL and the description. " +
        "The rollback is filled in too: the statements that undo each change, last change first."
    );
  });

  test("says what has to be done by hand when no rollback came with it", () => {
    saved(TWO_STATEMENTS);
    banner();
    expect(paragraphs()[0]).toBe(
      "Loading it points the editor at Billing prod, schema public, and fills in the SQL and the description. " +
        "It comes with no rollback, because at least one change has no statement that undoes it. " +
        "Before saving, write one in the Rollback SQL box, or tick Save without a rollback."
    );
  });

  test("warns nobody about overwriting an editor that is empty", () => {
    saved();
    banner();
    expect(paragraphs()).toHaveLength(1);
  });

  test("warns about it when the editor holds something", () => {
    saved();
    banner({ editorHasContent: true });
    expect(paragraphs()[1]).toBe(
      "Loading replaces the SQL, rollback and description the editor holds now."
    );
  });
});

describe("the load button", () => {
  test("offers to fill an empty editor in", () => {
    saved();
    banner();
    expect(load()).toBeEnabled();
  });

  test("says it will overwrite when there is something to overwrite", () => {
    // Same button, different promise. Somebody who reads only the button has to
    // be told there, not in the paragraph above it.
    saved();
    banner({ editorHasContent: true });
    expect(screen.getByRole("button", { name: "Replace the editor contents" })).toBeEnabled();
    expect(screen.queryByRole("button", { name: "Load into the editor" })).toBeNull();
  });

  test("waits for the saved connections, and says what it is waiting for", () => {
    // Loading early would point the editor nowhere and clear the draft, leaving
    // the person to work out which connection the script was written against.
    saved();
    banner({ connections: [], connectionsLoaded: false });
    expect(load()).toBeDisabled();
    expect(load()).toHaveAttribute("title", "Waiting for your saved connections to load.");
  });

  test("drops the explanation once there is nothing to explain", () => {
    saved();
    banner();
    expect(load()).not.toHaveAttribute("title");
  });

  test("hands the editor the draft itself, not the text it was stored as", () => {
    saved();
    banner();
    fireEvent.click(load());
    expect(onLoad).toHaveBeenCalledTimes(1);
    expect(onLoad).toHaveBeenCalledWith(ONE_STATEMENT);
  });

  test("forgets the draft, so it is not offered again on the next visit", () => {
    saved();
    banner();
    fireEvent.click(load());
    expect(stored()).toBeNull();
  });

  test("takes the offer away once it has been taken up", () => {
    saved();
    banner();
    fireEvent.click(load());
    expect(offer()).toBeNull();
  });
});

describe("the discard button", () => {
  test("forgets the draft without touching the editor", () => {
    saved();
    banner();
    fireEvent.click(discard());
    expect(onLoad).not.toHaveBeenCalled();
    expect(stored()).toBeNull();
  });

  test("takes the offer away", () => {
    saved();
    banner();
    fireEvent.click(discard());
    expect(offer()).toBeNull();
  });

  test("is offered whether or not the connections have arrived", () => {
    // Discard needs nothing from the network, and an offer that could not be
    // refused until a fetch came back would be a stuck banner on a slow line.
    saved();
    banner({ connections: [], connectionsLoaded: false });
    expect(discard()).toBeEnabled();
  });
});

describe("when the browser will not forget it", () => {
  // A browser can refuse to write to storage as easily as to read it — a
  // privacy setting, a full quota, a sandboxed frame. The removal is attempted
  // and not checked, so the banner has to remember being answered by itself.
  let removeItem: jest.SpyInstance;

  beforeEach(() => {
    removeItem = jest.spyOn(Storage.prototype, "removeItem").mockImplementation(() => {});
  });

  afterEach(() => removeItem.mockRestore());

  test("still takes the offer away after loading", () => {
    saved();
    banner();
    fireEvent.click(load());
    expect(stored()).not.toBeNull();
    expect(offer()).toBeNull();
  });

  test("and after discarding", () => {
    saved();
    banner();
    fireEvent.click(discard());
    expect(stored()).not.toBeNull();
    expect(offer()).toBeNull();
  });
});
