/**
 * The hand-over from a Performance tab to the Script Editor
 * (lib/migration-draft.ts).
 *
 * sessionStorage belongs to the browser, so each test puts a stand-in window
 * on globalThis: one whose storage works, one whose storage refuses every
 * call, and one where even looking the storage up throws, which is what a
 * browser that blocks site data does.
 */

import {
  MIGRATION_DRAFT_KEY,
  clearMigrationDraft,
  draftStatementCount,
  parseMigrationDraft,
  planDraftLoad,
  readMigrationDraftRaw,
  saveMigrationDraft,
  type MigrationDraft,
} from "@/lib/migration-draft";
import { MAX_MIGRATION_DESCRIPTION } from "@/lib/perf-sql";

/** A sessionStorage that works, kept in a Map. */
function workingStorage(): Storage {
  const map = new Map<string, string>();
  return {
    get length() {
      return map.size;
    },
    clear: () => map.clear(),
    getItem: (key: string) => map.get(key) ?? null,
    key: (index: number) => Array.from(map.keys())[index] ?? null,
    removeItem: (key: string) => {
      map.delete(key);
    },
    setItem: (key: string, value: string) => {
      map.set(key, String(value));
    },
  };
}

/** A sessionStorage that refuses every call, as a full or blocked one does. */
function refusingStorage(): Storage {
  const refuse = () => {
    throw new Error("The operation is insecure.");
  };
  return { length: 0, clear: refuse, getItem: refuse, key: refuse, removeItem: refuse, setItem: refuse };
}

function setWindow(value: unknown): void {
  Object.defineProperty(globalThis, "window", { value, configurable: true, writable: true });
}

afterEach(() => {
  Reflect.deleteProperty(globalThis, "window");
});

const draft: MigrationDraft = {
  sql:
    "-- Generated by Schema Studio. Review before running.\n\n" +
    "-- Foreign key has no index (orders.customer_id)\n" +
    'CREATE INDEX "orders_customer_id_idx" ON "public"."orders" ("customer_id");\n',
  rollbackSql: 'DROP INDEX "public"."orders_customer_id_idx";\n',
  description: "Performance fixes for public: Foreign key has no index (orders.customer_id)",
  connectionId: "3",
  schema: "public",
  createdAt: "2026-09-14T10:32:45.000Z",
};

describe("saving and reading the draft", () => {
  it("keeps the draft under its key, reads it back, and forgets it", () => {
    const storage = workingStorage();
    setWindow({ sessionStorage: storage });
    expect(saveMigrationDraft(draft)).toBe(true);
    expect(storage.getItem(MIGRATION_DRAFT_KEY)).not.toBeNull();
    expect(parseMigrationDraft(readMigrationDraftRaw())).toEqual(draft);
    clearMigrationDraft();
    expect(readMigrationDraftRaw()).toBeNull();
  });

  it("hands back the very same text on every read, as useSyncExternalStore needs", () => {
    setWindow({ sessionStorage: workingStorage() });
    saveMigrationDraft(draft);
    const first = readMigrationDraftRaw();
    expect(typeof first).toBe("string");
    expect(Object.is(first, readMigrationDraftRaw())).toBe(true);
  });

  it("says the save failed, and reads nothing, when the storage refuses every call", () => {
    setWindow({ sessionStorage: refusingStorage() });
    expect(saveMigrationDraft(draft)).toBe(false);
    expect(readMigrationDraftRaw()).toBeNull();
    expect(() => clearMigrationDraft()).not.toThrow();
  });

  it("does the same when even looking up sessionStorage throws", () => {
    setWindow(
      Object.defineProperty({}, "sessionStorage", {
        get() {
          throw new Error("Access is denied for this document.");
        },
      })
    );
    expect(saveMigrationDraft(draft)).toBe(false);
    expect(readMigrationDraftRaw()).toBeNull();
    expect(() => clearMigrationDraft()).not.toThrow();
  });

  it("saves and reads nothing on the server, where there is no window", () => {
    expect(typeof window).toBe("undefined");
    expect(saveMigrationDraft(draft)).toBe(false);
    expect(readMigrationDraftRaw()).toBeNull();
    expect(() => clearMigrationDraft()).not.toThrow();
  });
});

describe("parseMigrationDraft", () => {
  it("accepts a draft with no rollback", () => {
    const noRollback = { ...draft, rollbackSql: null };
    expect(parseMigrationDraft(JSON.stringify(noRollback))).toEqual(noRollback);
  });

  it("is null for nothing stored, for text that is not JSON, and for JSON that is not a draft", () => {
    expect(parseMigrationDraft(null)).toBeNull();
    expect(parseMigrationDraft("{not json")).toBeNull();
    expect(parseMigrationDraft("null")).toBeNull();
    expect(parseMigrationDraft('"a string"')).toBeNull();
    expect(parseMigrationDraft(JSON.stringify({ ...draft, sql: 42 }))).toBeNull();
    expect(parseMigrationDraft(JSON.stringify({ ...draft, rollbackSql: 7 }))).toBeNull();
    expect(parseMigrationDraft(JSON.stringify({ ...draft, connectionId: 3 }))).toBeNull();
    const { createdAt: _dropped, ...missing } = draft;
    void _dropped;
    expect(parseMigrationDraft(JSON.stringify(missing))).toBeNull();
  });

  it("is null for a draft with nothing to run, or no schema", () => {
    expect(parseMigrationDraft(JSON.stringify({ ...draft, sql: "-- only a comment\n;" }))).toBeNull();
    expect(parseMigrationDraft(JSON.stringify({ ...draft, schema: " " }))).toBeNull();
  });
});

describe("draftStatementCount", () => {
  it("counts the statements, not the comments around them", () => {
    const sql =
      "-- Generated by Schema Studio. Review before running.\n\n" +
      '-- First\nCREATE INDEX "a_idx" ON "public"."t" ("a");\n\n' +
      "-- Second\n-- Nothing more to run: the same SQL is already above.\n\n" +
      '-- Third\nDROP INDEX "public"."b_idx";\n';
    expect(draftStatementCount(sql)).toBe(2);
    expect(draftStatementCount("-- nothing\n;")).toBe(0);
  });

  it("does not count a semicolon inside a quoted name", () => {
    expect(draftStatementCount('CREATE INDEX "a;b" ON "public"."t" ("a");')).toBe(1);
  });
});

describe("planDraftLoad", () => {
  const editor = { connectionIds: ["1", "3"], connectionId: "1", schema: "sales" };

  it("fills in the script, its rollback and its description, and points the editor at the draft's schema", () => {
    expect(planDraftLoad(draft, editor)).toEqual({
      sql: draft.sql,
      rollbackSql: draft.rollbackSql,
      description: draft.description,
      target: { connectionId: "3", schema: "public" },
      resetFamily: true,
    });
  });

  it("keeps the chosen script family when the editor already points at the same place", () => {
    const same = planDraftLoad(draft, { ...editor, connectionId: "3", schema: "public" });
    expect(same.target).toEqual({ connectionId: "3", schema: "public" });
    expect(same.resetFamily).toBe(false);
  });

  it("leaves the target alone when the draft's connection is no longer saved", () => {
    const gone = planDraftLoad({ ...draft, connectionId: "9" }, editor);
    expect(gone.target).toBeNull();
    expect(gone.resetFamily).toBe(false);
    expect(gone.sql).toBe(draft.sql);
  });

  it("empties the rollback box when the draft has no rollback, rather than keep the old one", () => {
    expect(planDraftLoad({ ...draft, rollbackSql: null }, editor).rollbackSql).toBe("");
  });

  it("keeps the description within the push route's limit", () => {
    const long = planDraftLoad({ ...draft, description: "x".repeat(1500) }, editor);
    expect(long.description).toHaveLength(MAX_MIGRATION_DESCRIPTION);
  });
});
